import Head from 'next/head'

import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {data.map(user =>(
        <div>
          <h2>{user.name}</h2>
        </div>
      ))} */}

    </div>
  )
}
