import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dynamic route</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Dynamic Routes in Next.js</h1>
      <p className='desc'>select any of the API types to begin</p>
      <div className='btn-container'>
        <Link href={'/rest/home'}>
          <button className="btn">
            REST API
          </button>
        
        </Link>
        <Link href={'/graphql/home'}>
          <button className="btn">
            Graphql API
          </button>
        
        </Link>
      </div>
    </div>
  )
}
