import Head from 'next/head'

import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dynamic route</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Dynamic Routes</h1>
      <p className='desc'>select any of the API types to begin</p>
      <div className='btn-container'>
        <button className="btn">
          REST API
        </button>
        <button className="btn">
          Graphql API
        </button>
      </div>
    </div>
  )
}
